version: '3'

services:
  best-friends:
    image: deweiliu/chenyiyu:latest
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 80:80
    container_name: chenyiyu-container