name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag deweiliu/chenyiyu:latest
          docker login --username deweiliu --password ${{ secrets.docker_access }}
          docker push deweiliu/chenyiyu:latest
          docker logout

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update App service on Azure
        run: |
          az webapp restart --name chen-yiyu --resource-group app-services

      - name: Logout Azure
        run: |
          az logout
